name: Angular CI/CD with GitOps

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --configuration=production

      # Générer un tag unique pour chaque build
      - name: Generate image tag
        id: image_tag
        run: echo "tag=$(date +%Y%m%d-%H%M%S)-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            fadal1011/autoecole:${{ steps.image_tag.outputs.tag }}
            fadal1011/autoecole:latest

      # Mettre à jour le manifeste Kubernetes dans le repo GitOps
      - name: Update Kubernetes manifest
        if: github.ref == 'refs/heads/main'
        env:
          GIT_TOKEN: ${{ secrets.GIT_ARGO_TOKEN }}
          IMAGE_TAG: ${{ steps.image_tag.outputs.tag }}
        run: |
          # Configuration Git
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          # Clone le repo GitOps avec le token
          git clone https://${GIT_TOKEN}@github.com/ton-username/autoecole-gitops.git
          cd autoecole-gitops

          # Mettre à jour l'image dans deployment.yaml
          sed -i "s|image: fadal1011/autoecole:.*|image: fadal1011/autoecole:${IMAGE_TAG}|g" k8s/deployment.yaml

          # Commit et push les changements
          git add k8s/deployment.yaml
          git commit -m "chore: update image to ${IMAGE_TAG}" || echo "No changes to commit"
          git push origin main
